services:
  - type: web
    name: movie-catalog-web
    env: ruby
    plan: starter
    buildCommand: |
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      npm install --global yarn
      yarn install --check-files
      bundle install
      bundle exec rake assets:precompile
      bundle exec rake db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movieCatalog
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
