services:
  - type: web
    name: projeto-Maino
    env: ruby
    plan: free
    buildCommand: |
      gem install bundler -v 2.5.11
      bundle _2.5.11_ install
      bundle exec rake assets:precompile
      bundle exec rake db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
