databases:
- name: movieCatalog             # Nome do recurso E nome da database (Postgres)
# A chave 'user' foi removida. O Render irá gerar um usuário seguro.

services:
- type: web
  name: movie-catalog-web
  env: ruby
  plan: starter
  buildCommand: bash ./bin/render-build.sh
  startCommand: bundle exec puma -C config/puma.rb
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: movieCatalog         # Referencia o recurso de base de dados acima
      property: connectionString

  - key: RAILS_MASTER_KEY
    # Chave 'value' removida. Isso força você a definir o valor no Dashboard do Render como um Segredo.
    sync: false                  # Instrução para NÃO sobrescrever o valor no Dashboard.