databases:
- name: movieCatalog             # Nome do recurso E nome da database (Postgres)
  plan: free                     # <-- ADICIONADO: Define explicitamente o plano gratuito.
  # A chave 'user' foi removida, o Render ir치 gerar um usu치rio seguro.

services:
- type: web
  name: movie-catalog-web
  env: ruby
  plan: starter                  # J치 est치 configurado corretamente para o plano gratuito (Web Service)
  buildCommand: bash ./bin/render-build.sh
  startCommand: bundle exec puma -C config/puma.rb
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: movieCatalog
      property: connectionString

  - key: RAILS_MASTER_KEY
    # Chave 'value' removida. Defina o valor no Dashboard.
    sync: false