database:
 - name: movie_catalog_production
  database: movie_catalog_production
  user: movie_catalog


services: 
  - type: web
    name: movie-catalog-web
    env: ruby
    plan: starter
    buildCommand: bash ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movie_catalog_production
          property: connectionString
        value: production
      - key: RAILS_MASTER_KEY
        sync: false