services:
  - type: web
    name: projeto-maino
    env: ruby
    buildCommand: bundle install && bundle exec rake assets:precompile db:migrate
    startCommand: bundle exec rails server -p $PORT
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
