databases:
  - name: moviecatalog
    databaseName: moviecatalog
    user: moviecatalog
    plan: free

services:
  - type: web
    plan: free
    name: moviecatalog
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: moviecatalog
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false