database:
 - name: movieCatalog
  database: movieCatalog
  user: Souzathos


services: 
  - type: web
    name: movie-catalog-web
    env: ruby
    plan: starter
    buildCommand: bash ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movieCatalog
          property: connectionString
        value: production
      - key: RAILS_MASTER_KEY
        sync: false