databases:
  - name: movieCatalog

services:
  - type: web
    name: movie-catalog-web
    env: ruby
    plan: starter
    buildCommand: bash ./bin/render-build.sh
    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movieCatalog
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

    # ✅ Instalar Node + Yarn antes do build dos assets
    buildFilter:
      - ruby/**/*.rb
      - app/assets/**
      - app/javascript/**

    # ✅ Node + Yarn Setup
    dockerCommand: |
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      npm install -g yarn
