default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: movie_catalog_development
  username: movie_catalog
  password: 123456
  host: localhost

test:
  <<: *default
  database: movie_catalog_test
  username: movie_catalog
  password: 123456
  host: localhost

production:
  <<: *default
  # Usa a DATABASE_URL fornecida pelo Render
  url: <%= ENV["DATABASE_URL"] %>

# ===============================================
# ✅ NOVO: Configuração para Action Cable (WebSockets)
# O Rails precisa disso para iniciar o servidor em produção.
# ===============================================
cable:
  # Usar o adaptador 'postgresql' é a forma mais simples,
  # pois reutiliza a mesma conexão do DATABASE_URL.
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>