default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: movie_catalog_development
  username: movie_catalog
  password: 123456
  host: localhost

test:
  <<: *default
  database: movie_catalog_test
  username: movie_catalog
  password: 123456
  host: localhost

production:
  # ATENÇÃO: Removemos "<<: *default" para evitar herdar configurações locais.
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

cable:
  adapter: postgresql 
  url: <%= ENV["DATABASE_URL"] %>